# Generated by Django 5.2.8 on 2025-12-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level', 'key']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='key',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('django', 'Django'), ('flask', 'Flask'), ('r', 'R'), ('rstudio', 'RStudio'), ('notion', 'Notion')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
