# Generated by Django 5.2.8 on 2025-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_options_remove_skill_name_skill_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('data', 'Data'), ('web', 'Web'), ('tools', 'Tools'), ('devops', 'DevOps'), ('workflow', 'Workflow')], default='tools', max_length=40),
        ),
        migrations.AlterField(
            model_name='skill',
            name='key',
            field=models.CharField(choices=[('python', 'Python'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('django', 'Django'), ('flask', 'Flask'), ('r', 'R'), ('rstudio', 'RStudio'), ('notion', 'Notion')], max_length=40, unique=True),
        ),
    ]
