# Generated by Django 5.2.8 on 2025-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_category_alter_skill_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('data', 'Data'), ('web', 'Web'), ('database', 'Database'), ('tools', 'Tools'), ('devops', 'DevOps')], default='tools', max_length=40),
        ),
        migrations.AlterField(
            model_name='skill',
            name='key',
            field=models.CharField(choices=[('python', 'Python'), ('html5', 'HTML'), ('css3', 'CSS'), ('django', 'Django'), ('flask', 'Flask'), ('r', 'R'), ('rstudio', 'RStudio'), ('notion', 'Notion'), ('sql', 'SQL'), ('git', 'Git'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('linux', 'Linux'), ('docker', 'Docker'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('neo4j', 'Neo4j'), ('jupyter', 'Jupyter'), ('sklearn', 'Scikit-learn'), ('numpy', 'NumPy'), ('pandas', 'Pandas'), ('matplotlib', 'Matplotlib'), ('seaborn', 'Seaborn'), ('pytest', 'Pytest'), ('vscode', 'VS Code'), ('excel', 'Excel'), ('powerbi', 'Power BI'), ('opencv', 'OpenCV')], max_length=40, unique=True),
        ),
    ]
