# Generated by Django 5.2.8 on 2025-12-14 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_category_alter_skill_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=220)),
                ('intro', models.TextField(blank=True, default='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portfolio.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.CharField(blank=True, default='', max_length=20)),
                ('year_to', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='portfolio.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
