# Generated by Django 5.2.9 on 2025-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutpage_aboutimage_aboutblock_timelineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('data', 'Data'), ('web', 'Web'), ('database', 'Database'), ('tools', 'Tools'), ('devops', 'DevOps')], default='tools', max_length=40),
        ),
    ]
