# Generated by Django 5.2.8 on 2025-12-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contactmessage_message_alter_skill_category'),
        ('portfolio', '0007_experience'),
    ]

    # CODEX-CHANGE START
    operations = [
    ]
    # CODEX-CHANGE END
