# Generated by Django 5.2.8 on 2025-12-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_merge_20251218_1937'),
    ]

    operations = [
        # CODEX-CHANGE START
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill'),
        ),
        # CODEX-CHANGE END
    ]
