# Generated by Django 5.2.8 on 2025-12-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
