# Generated by Django 5.2.8 on 2025-12-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_project_tech_stack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
